on:
  push:
    branches: [ master, actions ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # make sure it installed?
      - name: Install dependencies
        run: |
            sudo apt-get install jq curl -y

      # Obfuscate src/loader.lua > public/loader.lua
      - name: LuaObfuscator REST API
        shell: bash {0}
        run: |
            mkdir public
            curl -X POST https://luaobfuscator.com/api/obfuscator/newscript \
            -H "Content-type: multipart/form-data" \
            -H "apikey: test" \
            -F __preload=@stubs/__preload.lua \
            -F scripts/bastion//src/APL/APL=@Bastion/src/APL/APL.lua \
            -F scripts/bastion//src/Aura/Aura=@Bastion/src/Aura/Aura.lua \
            -F scripts/bastion//src/AuraTable/AuraTable=@Bastion/src/AuraTable/AuraTable.lua \
            -F scripts/bastion//src/Cache/Cache=@Bastion/src/Cache/Cache.lua \
            -F scripts/bastion//src/Cacheable/Cacheable=@Bastion/src/Cacheable/Cacheable.lua \
            -F scripts/bastion//src/Class/Class=@Bastion/src/Class/Class.lua \
            -F scripts/bastion//src/ClassMagic/ClassMagic=@Bastion/src/ClassMagic/ClassMagic.lua \
            -F scripts/bastion//src/Command/Command=@Bastion/src/Command/Command.lua \
            -F scripts/bastion//src/EventManager/EventManager=@Bastion/src/EventManager/EventManager.lua \
            -F scripts/bastion//src/Item/Item=@Bastion/src/Item/Item.lua \
            -F scripts/bastion//src/ItemBook/ItemBook=@Bastion/src/ItemBook/ItemBook.lua \
            -F scripts/bastion//src/Library/Library=@Bastion/src/Library/Library.lua \
            -F scripts/bastion//src/List/List=@Bastion/src/List/List.lua \
            -F scripts/bastion//src/Module/Module=@Bastion/src/Module/Module.lua \
            -F scripts/bastion//src/MythicPlusUtils/MythicPlusUtils=@Bastion/src/MythicPlusUtils/MythicPlusUtils.lua \
            -F scripts/bastion//src/NotificationsList/NotificationsList=@Bastion/src/NotificationsList/NotificationsList.lua \
            -F scripts/bastion//src/ObjectManager/ObjectManager=@Bastion/src/ObjectManager/ObjectManager.lua \
            -F scripts/bastion//src/Refreshable/Refreshable=@Bastion/src/Refreshable/Refreshable.lua \
            -F scripts/bastion//src/Sequencer/Sequencer=@Bastion/src/Sequencer/Sequencer.lua \
            -F scripts/bastion//src/Spell/Spell=@Bastion/src/Spell/Spell.lua \
            -F scripts/bastion//src/SpellBook/SpellBook=@Bastion/src/SpellBook/SpellBook.lua \
            -F scripts/bastion//src/Timer/Timer=@Bastion/src/Timer/Timer.lua \
            -F scripts/bastion//src/Unit/Unit=@Bastion/src/Unit/Unit.lua \
            -F scripts/bastion//src/UnitManager/UnitManager=@Bastion/src/UnitManager/UnitManager.lua \
            -F scripts/bastion//src/Vector3/Vector3=@Bastion/src/Vector3/Vector3.lua \
            -F _bastion=@Bastion/src/_bastion.lua \
            -F __postload=@stubs/__postload.lua \
            | curl -X POST https://luaobfuscator.com/api/obfuscator/obfuscate \
            -H "Content-type: application/json" \
            -H "apikey: test" \
            --data "@config.json" \
            -H "sessionId: $(grep -o -P '(?<="sessionId":").*(?="})')" \
            --connect-timeout 120 \
            | jq -r ".code" \
            > public/_bastion.lua

      # publish public/loader.lua
      - name: Create artifact
        uses: actions/upload-artifact@v1
        with:
          name: release_protected
          path: public/
